// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpHOzQhOYdRZulRyIv9U8NI76JSeu4Gx8',
    appId: '1:145396806527:web:bce6815ac12fbaf0a5a04a',
    messagingSenderId: '145396806527',
    projectId: 'flutter-81ea7',
    authDomain: 'flutter-81ea7.firebaseapp.com',
    storageBucket: 'flutter-81ea7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4ShqnUqSLziCuzgSxcjuQ64dRXK1_5Y',
    appId: '1:145396806527:android:b293363b3fb0b381a5a04a',
    messagingSenderId: '145396806527',
    projectId: 'flutter-81ea7',
    storageBucket: 'flutter-81ea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHLUdsr9O95RjuTC0PaCNMHQQOeVSO9DE',
    appId: '1:145396806527:ios:129f82c357d280b7a5a04a',
    messagingSenderId: '145396806527',
    projectId: 'flutter-81ea7',
    storageBucket: 'flutter-81ea7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHLUdsr9O95RjuTC0PaCNMHQQOeVSO9DE',
    appId: '1:145396806527:ios:dea29639aa374300a5a04a',
    messagingSenderId: '145396806527',
    projectId: 'flutter-81ea7',
    storageBucket: 'flutter-81ea7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
